export const data = [
  {
    id: 1,
    nome: "luca",
    cognome: "rossi",
    email: "luca.rossi@gmmaaaaailit",
    codiceFiscale: "kdrwde32f93x109m",
    indirizzo: "via torino",
  },
  {
    id: 2,
    nome: "marco",
    cognome: "verdi",
    email: "marco.verdi@gmmaaaaailit",
    codiceFiscale: "gbbfrw54f32x176p",
    indirizzo: "via piacenza",
  },
  {
    id: 3,
    nome: "giulia",
    cognome: "bianchi",
    email: "giulia.bianchi@gmail.it",
    codiceFiscale: "abcde12345xyz",
    indirizzo: "via roma",
  },
  {
    id: 4,
    nome: "paolo",
    cognome: "rossi",
    email: "paolo.rossi@gmail.it",
    codiceFiscale: "defgh67890uvw",
    indirizzo: "via milano",
  },
  {
    id: 5,
    nome: "sara",
    cognome: "verdi",
    email: "sara.verdi@gmail.it",
    codiceFiscale: "ijklm54321rst",
    indirizzo: "via venezia",
  },
  {
    id: 6,
    nome: "andrea",
    cognome: "rossi",
    email: "andrea.rossi@gmail.it",
    codiceFiscale: "nopqr98765lmn",
    indirizzo: "via firenze",
  },
  {
    id: 7,
    nome: "laura",
    cognome: "verdi",
    email: "laura.verdi@gmail.it",
    codiceFiscale: "stuvw87654kji",
    indirizzo: "via napoli",
  },
  {
    id: 8,
    nome: "giorgio",
    cognome: "bianchi",
    email: "giorgio.bianchi@gmail.it",
    codiceFiscale: "xyz12345abcde",
    indirizzo: "via bologna",
  },
  {
    id: 9,
    nome: "anna",
    cognome: "rossi",
    email: "anna.rossi@gmail.it",
    codiceFiscale: "def456789wxy",
    indirizzo: "via palermo",
  },
  {
    id: 10,
    nome: "mario",
    cognome: "verdi",
    email: "mario.verdi@gmail.it",
    codiceFiscale: "ghi987654jkl",
    indirizzo: "via genova",
  },
];